baseURL = "http://asheetbhaskar.net/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Asheet Bhaskar"
publishDir= "docs"

# Change the default theme to be use when building the site with Hugo
theme = "anatole"

[params]
  contentratio = 0.8
